export enum StatusType {
  STUNNED = "STUNNED",
  ON_FIRE = "ON_FIRE",
  ACID = "ACID",
  MARKED = "MARKED",
  DEAD = "DEAD",
  DESTROYED = "DESTROYED",
  SANDEVISTAN = "SANDEVISTAN",
  ADRENAL_BOOSTER = "ADRENAL_BOOSTER",
}
